### ISSUE TITLE
does not work on colab

### ISSUE THREAD

**Issue by 0wwafa** [murat-dogan/node-datachannel#254]
```
added 733 packages from 541 contributors and audited 748 packages in 32.626s

74 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (7 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> node-datachannel@0.9.1 _prebuild /root/node_modules/node-datachannel
> prebuild -r napi --backend cmake-js

prebuild info begin Prebuild version 12.1.0
prebuild WARN This package does not support N-API version undefined 
prebuild ERR! build TypeError: expected first argument to be an array
prebuild ERR! build     at each (/root/node_modules/node-datachannel/node_modules/each-series-async/index.js:21:8)
prebuild ERR! build     at Object.<anonymous> (/root/node_modules/node-datachannel/node_modules/prebuild/bin.js:51:3)
prebuild ERR! build     at Module._compile (internal/modules/cjs/loader.js:1063:30)
prebuild ERR! build     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
prebuild ERR! build     at Module.load (internal/modules/cjs/loader.js:928:32)
prebuild ERR! build     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
prebuild ERR! build     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
prebuild ERR! build     at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! node-datachannel@0.9.1 _prebuild: `prebuild -r napi --backend cmake-js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the node-datachannel@0.9.1 _prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-06-06T11_02_38_749Z-debug.log
npm WARN notsup Unsupported engine for node-datachannel@0.9.1: wanted: {"node":">=16.0.0"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: node-datachannel@0.9.1
npm WARN notsup Unsupported engine for node-domexception@2.0.1: wanted: {"node":">=16"} (current: {"node":"14.16.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: node-domexception@2.0.1
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! node-datachannel@0.9.1 install: `prebuild-install -r napi || (npm install --ignore-scripts --production=false && npm run _prebuild)`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the node-datachannel@0.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-06-06T11_02_40_342Z-debug.log

```

**Comment by achingbrain** [comment]
You need to upgrade the version of node you are running - `14.16.0` is too old.
