### ISSUE TITLE
can not run on centos 7.9

### ISSUE THREAD

**Issue by YHS2017** [murat-dogan/node-datachannel#298]
[yhs@vbox server]$ npm run start

> lockstepdemo@1.0.0 start
> ts-node index.ts

Error: Cannot find module '../../build/Release/node_datachannel.node'
Require stack:
- /home/yhs/workspace/server/node_modules/node-datachannel/dist/cjs/lib/node-datachannel.cjs
- /home/yhs/workspace/server/node_modules/node-datachannel/dist/cjs/lib/index.cjs
- /home/yhs/workspace/server/rooms/lockstep.ts
- /home/yhs/workspace/server/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/yhs/workspace/server/node_modules/node-datachannel/src/lib/node-datachannel.ts:9:23)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
[yhs@vbox server]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[yhs@vbox server]$ npm list
lockstepdemo@1.0.0 /home/yhs/workspace/server
├── colyseus@0.9.33
├── express@4.21.1
├── node-datachannel@0.20.0
├── notepack.io@2.3.0
├── ts-node@5.0.1
└── typescript@3.9.10

**Comment by murat-dogan** [comment]
It can not find the addon binary.
Could you send also `npm install` command result?

This command normally should download the prebuilt binary from github. If it can not find it, it should try to compile.

**Comment by mirsella** [comment]
hello

im having the same problem with for a nitrojs server (for a nuxtapp, im using webtorrent, which use this plugin deep).
im on linux too, with node v23.1.0
```
[worker reload] [Error: [worker init] /home/mirsella/dev/nitro-app/.nitro/dev/index.mjs failed] {
  [cause]: Error: Cannot find module '../../build/Release/node_datachannel.node'
  Require stack:
  - /home/mirsella/dev/nitro-app/node_modules/.pnpm/node-datachannel@0.21.0/node_modules/node-datachannel/dist/esm/lib/node-datachannel.mjs
      at Function._resolveFilename (node:internal/modules/cjs/loader:1246:15)
      at Function._load (node:internal/modules/cjs/loader:1072:27)
      at TracingChannel.traceSync (node:diagnostics_channel:322:14)
      at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
      at Module.require (node:internal/modules/cjs/loader:1337:12)
      at require (node:internal/modules/helpers:139:16)
      at file:///home/mirsella/dev/nitro-app/node_modules/.pnpm/node-datachannel@0.21.0/node_modules/node-datachannel/dist/esm/lib/node-datachannel.mjs:13:21
      at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/mirsella/dev/nitro-app/node_modules/.pnpm/node-datachannel@0.21.0/node_modules/node-datachannel/dist/esm/lib/node-datachannel.mjs'
    ]
  }
}
```
reproduction: https://github.com/mirsella/node-datachannel-nitro (`pnpm i && pnpm dev`)

thanks

**Comment by mirsella** [comment]
i just tested with a empty deno project
```ts
import nodeDataChannel from "npm:node-datachannel";

nodeDataChannel.initLogger("Debug");
```
and error
```error: Uncaught (in promise) Error: Cannot find module '../../build/Release/node_datachannel.node'
Require stack:
- /home/mirsella/.cache/deno/npm/registry.npmjs.org/node-datachannel/0.20.0-alpha.2/dist/esm/lib/node-datachannel.mjs
    at Function.Module._resolveFilename (node:module:608:15)
    at Function.Module._load (node:module:486:27)
    at Module.require (node:module:674:19)
    at require (node:module:801:16)
    at file:///home/mirsella/.cache/deno/npm/registry.npmjs.org/node-datachannel/0.20.0-alpha.2/dist/esm/lib/node-datachannel.mjs:13:21
   ```

so its not just nitrojs

**Comment by murat-dogan** [comment]
Thank you for your notes.
I don't have a Centos. But probably it is related to the GLIBC version.

Can node 23 run on Centos 7?
I am asking while v7 is old. 

If I download a VM here, can I install node 23 and regenerate the issue? Or do I need some other modifications?

https://www.linuxvmimages.com/images/centos-7/

**Comment by mirsella** [comment]
for my it's on archlinux, so far from CentOS

**Comment by murat-dogan** [comment]
I am on Ubuntu 22.04 and I have tested your repo.
No problem for me. 
I have tried with node v20 and v23.

Do you see this file in place `build/Release/node_datachannel.node`?
Which version arch are you using and how I can re-generate it?

**Comment by mirsella** [comment]
thanks for the answer.

arch doesn't have release, so hard to get the exact version. I'll try to do a VM with a clean arch install to test.

the file is there in node module

**Comment by mirsella** [comment]
```
docker run -it --name arch archlinux sh
pacman -Sy git nodejs npm
git clone https://github.com/mirsella/node-datachannel-nitro
cd node-datachannel-nitro
npm i
npm run dev
```
then we just have to trigger the route hot reload.
`docker exec -it arch sh -c 'echo "" >> node-datachannel-nitro/server/routes/index.ts'`

**Comment by murat-dogan** [comment]
In my case there was no error
Here is console output;
```
[root@0e9c2546b4cd app]# npm i
(node:167) ExperimentalWarning: CommonJS module /usr/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.

> prepare
> nitro prepare


added 564 packages, and audited 566 packages in 15s

117 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[root@0e9c2546b4cd app]# npm run dev

> dev
> nitro dev


  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

✔ Nitro Server built in 305 ms                                                                                                                    nitro 7:18:35 PM
```

What is the difference?

**Comment by murat-dogan** [comment]
I have exactly these commands run.
https://github.com/murat-dogan/node-datachannel/issues/298#issuecomment-2491701912

except github clone, I have for easy working create a volume for the app folder

**Comment by murat-dogan** [comment]
Ooops sorry. Now I undestood your point. 
And got the same error.

**Comment by murat-dogan** [comment]
Please follow here
https://github.com/murat-dogan/node-datachannel/issues/310

**Comment by murat-dogan** [comment]
Can I close this issue?

**Comment by electricsteve** [comment]
I am still having this issue and I just can't for the life of me figure out why.
